# The playbook currently runs an echo command to print a fruit name. Apply a loop directive (with_items) to the task to print all fruits defined in the "fruits" variable.

# ------------------------------
#           BEFORE
# ------------------------------
#  name: Print list of fruits
#-
#  hosts: localhost
#  fruits:
#    - Apple
#    - Banana
#    - Grapes
#    - Orange
#  tasks:
#    -
#      command: echo "Apple"#
# ------------------------------
#           AFTER
# ------------------------------

-
  name: Print list of fruits
  hosts: localhost
  fruits:
    - Apple
    - Banana
    - Grapes
    - Orange
  tasks:
    -
      command: echo "{{ item }}"
      with_items: '{{ fruits }}'


# To a more realistic use case. We are attempting to install multiple packages using yum module.
# The current playbook installs only a single package.

# ------------------------------
#           BEFORE
# ------------------------------
#-
#  name: Install required packages
#  hosts: localhost
#  packages:
#      -	httpd
#      -	binutils
#      -	glibc
#      -	ksh
#      -	libaio
#      -	libXext
#      -	gcc
#      -	make
#      -	sysstat
#      -	unixODBC
#      -	mongodb
#      -	nodejs
#      -	grunt
#
#  tasks:
#    -
#      yum: name=httpd state=present
# ------------------------------
#           AFTER
# ------------------------------


-
  name: Install required packages
  hosts: localhost
  packages:
      -	httpd
      -	binutils
      -	glibc
      -	ksh
      -	libaio
      -	libXext
      -	gcc
      -	make
      -	sysstat
      -	unixODBC
      -	mongodb
      -	nodejs
      -	grunt

  tasks:
    -
      yum: name="{{ item }}" state=present
      with_items: "{{ packages }}"
