# Update the playbook with a play to "Execute a script on all web server nodes". The script is located at /tmp/install_script.sh
-
  name: Execute a script on all web server nodes
  hosts: web_nodes
  tasks:
    -
      name: Execute a script on all web server nodes
      script: /tmp/install_script.sh    
  


# Update the playbook to add a new task at second position (right after adding entry to resolv.conf) to create a new web user.
# Use the "user" module for this. User details to be used are given below:
# Username: web_user
# uid: 1040
# group: developers
#
# user documentation

# BEFORE
# ---------------
#-
#  name: Setup web server on all nodes
#  hosts: web_nodes
#  tasks:
#    -
#      name: Update entry into /etc/resolv.conf
#      lineinfile:
#        path: /etc/resolv.conf
#        line: 'nameserver 10.1.250.10'
#
#    -
#      name: Execute a script
#      script: /tmp/install_script.sh
#
#    -
#      name: Start httpd service
#      service:
#        name: httpd
#        state: present

#
#

# AFTER
# ---------------

-
  name: Setup web server on all nodes
  hosts: web_nodes
  tasks:
    -
      name: Update entry into /etc/resolv.conf
      lineinfile:
        path: /etc/resolv.conf
        line: 'nameserver 10.1.250.10'
    -
      name: create a new web user
      user:
        name: web_user
        password: 'Test123'
        groups: # Empty by default, here we give it some groups
          - developers          
        state: present
        


# Update the playbook to add a new task in the beginning to add an entry into /etc/resolv.conf file for hosts. The line to be added is 'nameserver 10.1.250.10'
# Note the new task must be executed first, so place it accordingly.
# lineinfile documentation

# BEFORE
# ---------------
#-
#  name: Execute a script on all web server nodes and start httpd service
#  hosts: web_nodes
#  tasks:
#    -
#      name: Execute a script
#      script: /tmp/install_script.sh
#
#    -
#      name: Start httpd service
#      service:
#        name: httpd
#        state: present
#
#

# AFTER
# ---------------



-
  name: Execute a script on all web server nodes and start httpd service
  hosts: web_nodes
  tasks:
    -
      name: Update entry into /etc/resolv.conf
      lineinfile:
        path: /etc/resolv.conf
        line: 'nameserver 10.1.250.10'
    -
      name: Execute a script
      script: /tmp/install_script.sh
    -
      name: Start httpd service
      service:
        name: httpd
        state: present
        







# Update the playbook to add a new task to start httpd services on all nodes
# service module documentation

# BEFORE
# ---------------
#-
#  name: Execute a script on all web server nodes and start httpd service
#  hosts: web_nodes
#  tasks:
#    -
#      name: Execute a script
#      script: /tmp/install_script.sh

#

# AFTER
# ---------------





-
  name: Execute a script on all web server nodes and start httpd service
  hosts: web_nodes
  tasks:   
    -
      name: Execute a script
      script: /tmp/install_script.sh
    -
      name: Start httpd service
      service:
        name: httpd
        state: present
        
